spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
        hibernate.default_schema: SampleSchema
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
    connection-timeout: 3000
    max-lifetime: 50000
    maximum-pool-size: 10
    pool-name: HikariCP
    jdbc-url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    initialization-mode: always

---
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.36://localhost/SampleSchema?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
---
spring:
  config.activate.on-profile: dev
  flyway:
    enabled: false

---
spring:
  config.activate.on-profile: stg
  flyway:
    enabled: false
  jpa:
    hibernate.show-sql: true

---
spring:
  config.activate.on-profile: prod
  flyway:
    enabled: false
  datasource:
    db:
      writer:
        maximum-pool-size: 50
      reader:
        maximum-pool-size: 50
