spring:
  data:
    redis:
      timeout: 5s
      client-type: jedis
app:
  cache:
    localCaches:
      10m: maximumSize=100000, expireAfterWrite=10m, recordStats
      enum-age-types: maximumSize=6, expireAfterWrite=10m, recordStats
      enum-service-cd: maximumSize=4, expireAfterWrite=10m, recordStats
      enum-push-type: maximumSize=6, expireAfterWrite=10m, recordStats
      enum-prod-cd: maximumSize=9, expireAfterWrite=60m, recordStats
      set-terms: maximumSize=100, expireAfterWrite=30s, recordStats
      member-terms: maximumSize=100, expireAfterWrite=30s, recordStats
    redisCaches:
      30m: 30m
      user-info-cache: 10m
      getOauth2: 1m
      user-info-type: 5m

---
spring:
  config.activate.on-profile: local
  data:
    redis:
      host: ${REDIS_NODES_HOST}
      port: ${REDIS_NODES_PORT}

---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      cluster:
        nodes: ${REDIS_NODES_HOST}:${REDIS_NODES_PORT}
        max-redirects: 5
      ssl:
        enabled: true
---
spring:
  config.activate.on-profile: stg
  data:
    redis:
      cluster:
        nodes: ${REDIS_NODES_HOST}:${REDIS_NODES_PORT}
        max-redirects: 5
      ssl:
        enabled: true

---
spring:
  config.activate.on-profile: prod
  data:
    redis:
      cluster:
        nodes: ${REDIS_NODES_HOST}:${REDIS_NODES_PORT}
        max-redirects: 5
      ssl:
        enabled: true
